name = "swindlestones_durable_objects"
main = "./dist/index.mjs"
compatibility_date = "2023-11-25"

[build]
command = "npm install && npm run build"

[durable_objects]
bindings = [{name = "LOBBYMANAGER", class_name = "LobbyManager"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["LobbyManager"]
